#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Contribute! Source on GitHub":
      - "https://github.com/twofaktor/minibolt"

color_scheme: minibolt-dark.scss

# defaults
defaults:
  - scope:
      path: ""
    values:
      image: https://twofaktor.github.io/minibolt/images/minibolt-home-screen.png

# jekyll-seo-tag
twitter:
  card: summary_large_image
  username: twofaktor

title: MiniBolt-draft
tagline: "Bitcoin & Lightning on a Personal Computer"
description: "Build your own “DIY” Bitcoin & Lightning full node on a personal computer. No need to trust anyone else."
type: website

# enable theme for local usage
#theme: "just-the-docs"
